import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'
import { ProductExperiencePanel } from './features/productexperience/ProductExperiencePanel'
import { ProjectProvisioningWizard } from './features/project/ProjectProvisioningWizard'
import { ProjectMembersPanel } from './features/project/ProjectMembersPanel'
import { WorkspaceNavigation } from './features/navigation/WorkspaceNavigation'
import { AuthPanel, type AuthState, type AuthUser } from './features/auth/AuthPanel'

type Project = { id: string; name: string; slug: string; status: string; runtime_id?: string }
type Health = { application: string; runtime: string; reason?: string }
type Agent = { id: string; display_name: string; adapter: string; status: string }
type AgentSession = { id: string; project_id: string; agent_id: string; status: string; runtime_id: string; working_directory: string }
type AgentEvent = { type: string; normalized?: { text?: string }; raw?: Record<string, unknown> }
type Model = { id: string; provider_id: string; display_name: string; context_window: number; local: boolean; remote: boolean; coding: boolean; reasoning: boolean; tool_use: boolean }
type RoutingDecision = { selected_model?: { provider_id: string; model_id: string }; reason?: string; alternatives?: { model: { provider_id: string; model_id: string }; score: number }[]; estimated_cost?: number; confidence?: number }
type Workflow = { id: string; goal: string; status: string; strategy: string; graph: { tasks: Record<string, { title: string; status: string; dependencies: string[]; task_type: string }> } }
type Verification = { id: string; status: string; project_id: string; summary: { required_passed: number; required_failed: number; optional_passed: number; optional_failed: number; blocked: number }; results: { check_id: string; status: string; evidence?: { exit_code?: number; stdout?: string; stderr?: string; commit_sha?: string }; failure?: { failure_type: string; suspected_cause: string } }[]; failures: { failure_type: string; check_id: string; suspected_cause: string }[]; repairs: { attempt: number; status: string; error?: string }[]; state?: { commit_sha?: string; worktree?: string } }
type AIRuntime = { spec: { id: string; kind: string; endpoint: string; local: boolean }; capabilities: Record<string, boolean>; health: { status: string; latency?: number; available_models?: string[]; error?: string } }
type AIModel = { id: string; runtime_id: string; display_name: string; status: string; context_window: number; local: boolean; capabilities: Record<string, boolean>; latency?: number }
type Hardware = { cpu_cores: number; memory_total: number; memory_available: number; gpu_count: number; gpu_memory_total: number; gpus?: { id: string; model: string; memory_total: number; memory_available: number }[] }
type Deployment = { id: string; project_id: string; environment: string; version: string; source_revision: string; runtime_target: string; status: string; health_status?: string; failure_reason?: string; release_id?: string; created_at: string }
type IntelligenceAnalysis = { classification: { primary_type: string; confidence: number }; decision: { selected_id: string; selected: { framework: string; language: string; runtime: string; package_manager: string }; reasons: string[]; candidates: { id: string; compatibility: number; complexity: number }[] }; requirements: { description: string; priority: string; required: boolean }[] }
type ProvisioningRun = { id: string; status: string; progress?: number; runtime_id?: string; error?: string; steps?: { id: string; name: string; status: string; progress: number; cache_status?: string }[] }
type ProjectComputer = { id: string; project_id: string; runtime_provider: string; runtime_id?: string; image: string; status: string; readiness: string[]; capabilities: { capability: string; status: string; evidence?: string }[] }
type Resolution = { requirement: string; version: { version: string; artifact: { name: string } }; cache_status: string; reason: string }
type DesignSystem = { name: string; version: string; tokens: { name: string; kind: string; value: string }[]; components: { name: string; variants: { name: string }[] }[]; accessibility_rules: { name: string; severity: string }[] }
type KnowledgeGraph = { nodes: { id: string; type: string; name: string; path?: string }[]; edges: { from: string; to: string; type: string }[] }
type ProductActivity = { id: string; type: string; state: string; message: string; timestamp: string }
type ImpactAnalysis = { root_node: string; risk: string; files: string[]; apis: string[]; components: string[]; tests: string[]; approval_required: boolean; reasons: string[] }
type VisualQA = { status: string; reason?: string; results?: { viewport: string; status: string; evidence?: string }[] }
type GovernanceDecision = { effect: string; reason: string; action?: { permission: string; risk: string; resource?: string } }
type LoopExecution = { id: string; project_id: string; goal?: string; status: string; current_stage?: string; error?: string; results?: Record<string, { state: string; message: string }> }
const API = import.meta.env.VITE_API_URL ?? ''
const apiFetch = (input: RequestInfo | URL, init: RequestInit = {}) => fetch(input, { ...init, credentials: 'include' })

export default function App() {
  const [auth, setAuth] = useState<AuthState | null>(null)
  const [authChecking, setAuthChecking] = useState(true)
  const [projects, setProjects] = useState<Project[]>([])
  const [name, setName] = useState('hello-world')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [health, setHealth] = useState<Health | null>(null)
  const [agents, setAgents] = useState<Agent[]>([])
  const [selectedProject, setSelectedProject] = useState('')
  const [selectedAgent, setSelectedAgent] = useState('codex')
  const [session, setSession] = useState<AgentSession | null>(null)
  const [agentEvents, setAgentEvents] = useState<AgentEvent[]>([])
  const [message, setMessage] = useState('')
  const [models, setModels] = useState<Model[]>([])
  const [routingPolicy, setRoutingPolicy] = useState('BALANCED')
  const [routingDecision, setRoutingDecision] = useState<RoutingDecision | null>(null)
  const [workflowGoal, setWorkflowGoal] = useState('Build and verify a small feature')
  const [workflow, setWorkflow] = useState<Workflow | null>(null)
  const [verification, setVerification] = useState<Verification | null>(null)
  const [verificationBusy, setVerificationBusy] = useState(false)
  const [aiRuntimes, setAiRuntimes] = useState<AIRuntime[]>([])
  const [aiModels, setAiModels] = useState<AIModel[]>([])
  const [hardware, setHardware] = useState<Hardware | null>(null)
  const [aiPolicy, setAiPolicy] = useState('BALANCED')
  const [aiLocalOnly, setAiLocalOnly] = useState(false)
  const [deployments, setDeployments] = useState<Deployment[]>([])
  const [deployEnvironment, setDeployEnvironment] = useState('development')
  const [deployVersion, setDeployVersion] = useState('v1')
  const [deployRevision, setDeployRevision] = useState('HEAD')
  const [deployRuntime, setDeployRuntime] = useState('')
  const [deployHealthTarget, setDeployHealthTarget] = useState('curl -fsS http://127.0.0.1/health')
  const [wizardPrompt, setWizardPrompt] = useState('أريد تطبيقًا ويب بسيطًا قابلًا للتحقق والنشر.')
  const [wizardPlatforms, setWizardPlatforms] = useState('web')
  const [wizardStep, setWizardStep] = useState(1)
  const [wizardAnalysis, setWizardAnalysis] = useState<IntelligenceAnalysis | null>(null)
  const [wizardManifest, setWizardManifest] = useState<Record<string, unknown> | null>(null)
  const [wizardRun, setWizardRun] = useState<ProvisioningRun | null>(null)
  const [wizardBusy, setWizardBusy] = useState(false)
  const [projectComputers, setProjectComputers] = useState<ProjectComputer[]>([])
  const [openComputer, setOpenComputer] = useState<ProjectComputer | null>(null)
  const [openComputerBusy, setOpenComputerBusy] = useState(false)
  const [currentUser, setCurrentUser] = useState<AuthUser | null>(null)
  const [environmentResolutions, setEnvironmentResolutions] = useState<Resolution[]>([])
  const [cacheStats, setCacheStats] = useState<Record<string, number> | null>(null)
  const [designSystem, setDesignSystem] = useState<DesignSystem | null>(null)
  const [knowledgeGraph, setKnowledgeGraph] = useState<KnowledgeGraph | null>(null)
  const [productActivity, setProductActivity] = useState<ProductActivity[]>([])
  const [impact, setImpact] = useState<ImpactAnalysis | null>(null)
  const [impactNode, setImpactNode] = useState('')
  const [visualQA, setVisualQA] = useState<VisualQA | null>(null)
  const [visualQABusy, setVisualQABusy] = useState(false)
  const [governanceDecision, setGovernanceDecision] = useState<GovernanceDecision | null>(null)
  const [governancePermission, setGovernancePermission] = useState('terminal.execute')
  const [governanceRisk, setGovernanceRisk] = useState('EXECUTE')
  const [governanceResource, setGovernanceResource] = useState('project runtime')
  const [loopGoal, setLoopGoal] = useState('Build, verify, and deploy the selected project')
  const [loop, setLoop] = useState<LoopExecution | null>(null)
  const [loopBusy, setLoopBusy] = useState(false)
  useEffect(() => {
    let active = true
    apiFetch(`${API}/auth/me`).then(async (response) => {
      if (!response.ok) return null
      return await response.json() as AuthState
    }).then((payload) => {
      if (!active) return
      if (payload) { setAuth(payload); setCurrentUser(payload.user) }
      setAuthChecking(false)
    }).catch(() => { if (active) { setAuth(null); setAuthChecking(false) } })
    return () => { active = false }
  }, [])
  async function loadProjects(): Promise<Project[]> { const response = await apiFetch(`${API}/api/v1/projects`); if (!response.ok) throw new Error('تعذر تحميل المشاريع'); const items: Project[] = await response.json(); setProjects(items); return items }
  useEffect(() => { if (!auth) return; loadProjects().then((items) => { if (items[0]) setSelectedProject(items[0].id) }).catch((err) => setError(err.message)); apiFetch(`${API}/health`).then((response) => response.json()).then(setHealth).catch(() => setHealth({ application: 'UNKNOWN', runtime: 'UNKNOWN' })); apiFetch(`${API}/api/agents`).then((response) => response.ok ? response.json() : []).then(setAgents).catch(() => setAgents([])); apiFetch(`${API}/api/models`).then((response) => response.ok ? response.json() : []).then(setModels).catch(() => setModels([])); apiFetch(`${API}/api/ai/runtimes`).then((response) => response.ok ? response.json() : []).then(setAiRuntimes).catch(() => setAiRuntimes([])); apiFetch(`${API}/api/ai/models`).then((response) => response.ok ? response.json() : []).then(setAiModels).catch(() => setAiModels([])); apiFetch(`${API}/api/ai/hardware`).then((response) => response.ok ? response.json() : null).then(setHardware).catch(() => setHardware(null)) }, [auth])
  async function saveAISettings() { if (!selectedProject) return; const response = await apiFetch(`${API}/api/projects/${selectedProject}/ai-settings`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ routing_policy: aiPolicy, privacy_policy: aiLocalOnly ? 'PRIVATE' : 'PUBLIC', local_only: aiLocalOnly }) }); if (!response.ok) setError('تعذر حفظ إعدادات AI للمشروع') }
  useEffect(() => { if (!auth || !selectedProject) return; apiFetch(`${API}/api/projects/${selectedProject}/deployments`).then((response) => response.ok ? response.json() : []).then(setDeployments).catch(() => setDeployments([])); apiFetch(`${API}/api/project-computers?project_id=${selectedProject}`).then((response) => response.ok ? response.json() : []).then(setProjectComputers).catch(() => setProjectComputers([])); apiFetch(`${API}/api/cache/stats`).then((response) => response.ok ? response.json() : null).then((payload) => setCacheStats(payload?.stats ?? null)).catch(() => setCacheStats(null)); apiFetch(`${API}/api/projects/${selectedProject}/design`).then((response) => response.ok ? response.json() : null).then(setDesignSystem).catch(() => setDesignSystem(null)); apiFetch(`${API}/api/projects/${selectedProject}/knowledge/graph`).then((response) => response.ok ? response.json() : null).then(setKnowledgeGraph).catch(() => setKnowledgeGraph(null)); apiFetch(`${API}/api/projects/${selectedProject}/activity`).then((response) => response.ok ? response.json() : []).then(setProductActivity).catch(() => setProductActivity([])) }, [auth, selectedProject])
  useEffect(() => { if (!selectedProject || !loop || !['RUNNING', 'BLOCKED'].includes(loop.status)) return; const timer = window.setInterval(() => { apiFetch(`${API}/api/projects/${selectedProject}/autonomous-loop/${loop.id}`).then((response) => response.ok ? response.json() : null).then((payload) => payload && setLoop(payload)).catch(() => undefined) }, 1500); return () => window.clearInterval(timer) }, [selectedProject, loop?.id, loop?.status])
  async function startAutonomousLoop() { if (!selectedProject) { setError('اختر مشروعًا أولًا'); return }; setLoopBusy(true); setError(''); try { const response = await apiFetch(`${API}/api/projects/${selectedProject}/autonomous-loop/start`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ goal: loopGoal }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? 'تعذر تشغيل Autonomous Loop'); setLoop(payload) } catch (err) { setError(err instanceof Error ? err.message : 'تعذر تشغيل Autonomous Loop') } finally { setLoopBusy(false) } }
  async function resumeAutonomousLoop() { if (!selectedProject || !loop) return; const response = await apiFetch(`${API}/api/projects/${selectedProject}/autonomous-loop/${loop.id}/resume`, { method: 'POST' }); if (!response.ok) { setError((await response.json()).error ?? 'تعذر استئناف Autonomous Loop'); return }; setLoop((current) => current ? { ...current, status: 'RUNNING' } : current) }
  useEffect(() => { if (!auth || !selectedProject || typeof EventSource === 'undefined') return; const source = new EventSource(`${API}/api/projects/${selectedProject}/activity/stream`); const onActivity = (event: MessageEvent) => { try { const payload = JSON.parse(event.data) as { id?: string; type?: string; state?: string; message?: string; timestamp?: string }; setProductActivity((items) => [...items.slice(-99), { id: payload.id ?? `${Date.now()}`, type: payload.type ?? 'activity', state: payload.state ?? 'ACTIVE', message: payload.message ?? payload.type ?? 'activity', timestamp: payload.timestamp ?? new Date().toISOString() }]) } catch { /* malformed events remain visible only in server logs */ } }; source.addEventListener('project.activity', onActivity); return () => { source.removeEventListener('project.activity', onActivity); source.close() } }, [auth, selectedProject])
  async function createDeployment(event: FormEvent) { event.preventDefault(); if (!selectedProject) return; const response = await apiFetch(`${API}/api/projects/${selectedProject}/deployments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ environment: deployEnvironment, version: deployVersion, source_revision: deployRevision, runtime_target: deployRuntime || `${selectedProject}_runtime`, metadata: { verification_run_id: verification?.id, health_target: deployHealthTarget, build_argv: ['go', 'build', './...'], test_argv: ['go', 'test', './...'] } }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error?.message ?? 'تعذر إنشاء deployment'); return }; setDeployments((items) => [payload, ...items]) }
  async function rollbackDeployment(id: string) { const response = await apiFetch(`${API}/api/projects/${selectedProject}/deployments/${id}/rollback`, { method: 'POST' }); const payload = await response.json(); if (!response.ok) { setError(payload.error?.message ?? 'تعذر تنفيذ rollback'); return }; setDeployments((items) => items.map((item) => item.id === id ? payload : item)) }
  async function analyzeWizard() { if (!selectedProject) { setError('أنشئ مشروعًا أو اختر مشروعًا أولًا'); return }; setWizardBusy(true); setError(''); try { const response = await apiFetch(`${API}/api/projects/${selectedProject}/intelligence/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ user_prompt: wizardPrompt, platforms: wizardPlatforms.split(',').map((item) => item.trim()).filter(Boolean), constraints: [], preferences: [], budget: { prefer_local: true } }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? 'تعذر تحليل النية'); setWizardAnalysis(payload); setWizardStep(2) } catch (err) { setError(err instanceof Error ? err.message : 'تعذر تحليل النية') } finally { setWizardBusy(false) } }
  async function resolveWizardEnvironment(manifest: Record<string, unknown>) { const response = await apiFetch(`${API}/api/projects/${selectedProject}/environment/resolve`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(manifest) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? 'تعذر حل أدوات البيئة'); setEnvironmentResolutions(payload.resolutions ?? []) }
  async function createWizardManifest() { if (!selectedProject || !wizardAnalysis) return; setWizardBusy(true); try { const response = await apiFetch(`${API}/api/projects/${selectedProject}/environment/manifests`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ intent: { user_prompt: wizardPrompt, platforms: wizardPlatforms.split(',').map((item) => item.trim()).filter(Boolean) }, profile: 'STANDARD' }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? 'تعذر إنشاء manifest'); setWizardManifest(payload.manifest); setWizardAnalysis(payload.analysis); await resolveWizardEnvironment(payload.manifest); setWizardStep(3) } catch (err) { setError(err instanceof Error ? err.message : 'تعذر إنشاء manifest') } finally { setWizardBusy(false) } }
  async function planWizardProvisioning() { if (!selectedProject || !wizardManifest) return; setWizardBusy(true); try { const computerResponse = await apiFetch(`${API}/api/project-computers`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project_id: selectedProject, manifest: wizardManifest, available: { cpu: 2, memory_bytes: 4294967296, disk_bytes: 21474836480, network: true } }) }); const computerPayload = await computerResponse.json(); if (!computerResponse.ok) { if (computerPayload.project_computer) setProjectComputers((items) => [computerPayload.project_computer, ...items]); throw new Error(computerPayload.error ?? 'Project Computer is unavailable') } setProjectComputers((items) => [computerPayload, ...items]); const response = await apiFetch(`${API}/api/projects/${selectedProject}/provisioning/plans`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ manifest: wizardManifest, runtime_id: computerPayload.runtime_id }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? 'تعذر تخطيط provisioning'); setWizardRun(payload); setWizardStep(4); const start = await apiFetch(`${API}/api/provisioning/${payload.id}/start`, { method: 'POST' }); const started = await start.json(); setWizardRun(started) } catch (err) { setError(err instanceof Error ? err.message : 'تعذر تشغيل provisioning') } finally { setWizardBusy(false) } }
  async function createProject(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const response = await apiFetch(`${API}/api/v1/projects`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); if (!response.ok) throw new Error((await response.json()).error?.message ?? 'فشل إنشاء المشروع'); setName(''); await loadProjects() } catch (err) { setError(err instanceof Error ? err.message : 'حدث خطأ غير معروف') } finally { setLoading(false) } }
  async function changeStatus(project: Project, action: 'start' | 'stop') { setError(''); try { const response = await apiFetch(`${API}/api/v1/projects/${project.id}/${action}`, { method: 'POST' }); if (!response.ok) throw new Error((await response.json()).error?.message ?? 'فشل تغيير الحالة'); await loadProjects() } catch (err) { setError(err instanceof Error ? err.message : 'حدث خطأ غير معروف') } }
  async function openProjectComputer(project: Project) {
    setSelectedProject(project.id)
    setOpenComputerBusy(true)
    setError('')
    try {
      const computer = projectComputers.find((item) => item.project_id === project.id)
      if (!computer) throw new Error('لا توجد Project Computer مرتبطة بهذا المشروع')
      const response = await apiFetch(`${API}/api/project-computers/${computer.id}`)
      const payload = await response.json()
      if (!response.ok) throw new Error(payload.error ?? 'تعذر تحميل تفاصيل Project Computer')
      setOpenComputer(payload)
      window.requestAnimationFrame(() => document.getElementById('project-computer')?.scrollIntoView({ behavior: 'smooth', block: 'start' }))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'تعذر فتح Project Computer')
    } finally {
      setOpenComputerBusy(false)
    }
  }
  async function createAgentSession(event: FormEvent) { event.preventDefault(); if (!selectedProject) { setError('اختر مشروعًا أولًا'); return }; setError(''); try { const response = await apiFetch(`${API}/api/projects/${selectedProject}/agent-sessions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agent_id: selectedAgent, runtime_id: `${selectedProject}_runtime`, working_directory: '/workspace' }) }); if (!response.ok) throw new Error((await response.json()).error?.message ?? 'تعذر إنشاء الجلسة'); setSession(await response.json()); setAgentEvents([]) } catch (err) { setError(err instanceof Error ? err.message : 'حدث خطأ غير معروف') } }
  async function startAgentSession() { if (!session) return; const response = await apiFetch(`${API}/api/projects/${session.project_id}/agent-sessions/${session.id}/start`, { method: 'POST' }); const payload = await response.json(); if (!response.ok) { setError(payload.error?.message ?? 'تعذر تشغيل الجلسة'); return }; setSession(payload) }
  async function cancelAgentSession() { if (!session) return; const response = await apiFetch(`${API}/api/projects/${session.project_id}/agent-sessions/${session.id}/cancel`, { method: 'POST' }); const payload = await response.json(); if (!response.ok) { setError(payload.error?.message ?? 'تعذر إلغاء الجلسة'); return }; setSession(payload) }
  useEffect(() => { if (!session || !['STARTING', 'RUNNING', 'WAITING', 'RECOVERING'].includes(session.status)) return; const timer = window.setInterval(() => { apiFetch(`${API}/api/projects/${session.project_id}/agent-sessions/${session.id}/events`).then((response) => response.ok ? response.json() : []).then(setAgentEvents).catch(() => undefined) }, 1500); return () => window.clearInterval(timer) }, [session?.id, session?.status, session?.project_id])
  async function sendAgentMessage(event: FormEvent) { event.preventDefault(); if (!session || !message.trim()) return; const response = await apiFetch(`${API}/api/projects/${session.project_id}/agent-sessions/${session.id}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message }) }); if (!response.ok) setError((await response.json()).error?.message ?? 'تعذر إرسال الرسالة'); setMessage(''); const events = await apiFetch(`${API}/api/projects/${session.project_id}/agent-sessions/${session.id}/events`).then((r) => r.ok ? r.json() : []); setAgentEvents(events) }
  async function previewRouting(event: FormEvent) { event.preventDefault(); const response = await apiFetch(`${API}/api/model-routing/decide`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project_id: selectedProject, agent_id: selectedAgent, policy: routingPolicy, privacy_policy: 'PUBLIC', local_policy: 'REMOTE_ALLOWED', available_runtime: true, task_profile: { task_type: 'REFACTOR', context_required: 1000, reasoning_required: true, privacy_classification: 'PUBLIC' } }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error ?? 'لا يوجد نموذج متوافق'); setRoutingDecision(payload.decision ?? null); return }; setRoutingDecision(payload) }
  async function createWorkflow(event: FormEvent) { event.preventDefault(); if (!selectedProject) { setError('اختر مشروعًا أولًا'); return }; const response = await apiFetch(`${API}/api/projects/${selectedProject}/workflows`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ intent: { goal: workflowGoal } }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error?.message ?? 'تعذر إنشاء workflow'); return }; setWorkflow(payload) }
  async function runVerification() { if (!selectedProject) { setError('اختر مشروعًا أولًا'); return }; setVerificationBusy(true); setError(''); try { const response = await apiFetch(`${API}/api/verifications`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project_id: selectedProject, workflow_id: workflow?.id, profile: 'standard', policy: 'STANDARD', runtime_id: `${selectedProject}_runtime`, workspace: '/workspace', checks: [{ id: 'build', type: 'BUILD', name: 'Build', required: true, timeout: 600000000000, retry_policy: { max_attempts: 1 }, configuration: { argv: ['go', 'build', './...'] } }, { id: 'tests', type: 'UNIT_TEST', name: 'Tests', required: true, timeout: 600000000000, retry_policy: { max_attempts: 1 }, configuration: { argv: ['go', 'test', './...'] }, dependencies: ['build'] }] }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? 'تعذر تشغيل verification'); setVerification(payload) } catch (err) { setError(err instanceof Error ? err.message : 'تعذر تشغيل verification') } finally { setVerificationBusy(false) } }
  async function analyzeImpact() { if (!selectedProject || !impactNode.trim()) { setError('اختر عقدة من Knowledge Graph لتحليل التأثير'); return }; const response = await apiFetch(`${API}/api/projects/${selectedProject}/impact/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ root_node: impactNode.trim() }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error ?? 'تعذر تحليل التأثير'); return }; setImpact(payload) }
  async function evaluateGovernance() { if (!selectedProject) { setError('اختر مشروعًا لتقييم Governance'); return }; const constitutionResponse = await apiFetch(`${API}/api/projects/${selectedProject}/constitutions/${selectedAgent}`); if (!constitutionResponse.ok) { setGovernanceDecision({ effect: 'UNAVAILABLE', reason: 'لا توجد Constitution محفوظة لهذا agent' }); return }; const constitution = await constitutionResponse.json(); const response = await apiFetch(`${API}/api/projects/${selectedProject}/governance/evaluate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ constitution, action: { project_id: selectedProject, agent_id: selectedAgent, permission: governancePermission, risk: governanceRisk, resource: governanceResource, description: 'Frontend governance preflight' } }) }); const payload = await response.json(); setGovernanceDecision(payload) }
  async function runVisualQA() { if (!selectedProject || !projectComputers[0]) { setError('Visual QA requires a Project Computer'); return }; setVisualQABusy(true); setError(''); try { const response = await apiFetch(`${API}/api/projects/${selectedProject}/visual-qa`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ computer_id: projectComputers[0].id, target_url: '', viewports: [{ name: 'mobile', width: 390, height: 844 }, { name: 'tablet', width: 1024, height: 768 }, { name: 'desktop', width: 1440, height: 900 }] }) }); const payload = await response.json(); setVisualQA(payload); if (!response.ok) setError(payload.error ?? 'Visual QA is blocked') } catch (err) { setError(err instanceof Error ? err.message : 'Visual QA is blocked') } finally { setVisualQABusy(false) } }
  async function repairVerification() { if (!verification) return; setVerificationBusy(true); try { const response = await apiFetch(`${API}/api/verifications/${verification.id}/repair`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ runtime_id: `${selectedProject}_runtime`, workspace: '/workspace', max_attempts: 3 }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? 'تعذر بدء repair'); setVerification(payload) } catch (err) { setError(err instanceof Error ? err.message : 'تعذر بدء repair') } finally { setVerificationBusy(false) } }
  async function logout() { await apiFetch(`${API}/auth/logout`, { method: 'POST' }).catch(() => undefined); setAuth(null); setCurrentUser(null); setProjects([]); setSelectedProject('') }
  if (authChecking) return <main className="auth-shell" dir="rtl"><section className="auth-card"><div className="auth-loading">جاري التحقق من جلسة SUDA FORGE…</div></section></main>
  if (!auth) return <AuthPanel api={API} onAuthenticated={(state) => { setAuth(state); setCurrentUser(state.user) }} />
  return <main dir="rtl"><WorkspaceNavigation />
    <header><div><span className="eyebrow">SUDA TECHNOLOGIES</span><h1>SUDA FORGE</h1><p>كل مشروع هو Project Computer حقيقي، وليس مجرد مجلد أو نافذة محادثة.</p></div><div className="system"><span className="dot" /> Control Plane online {currentUser && <><span className="user-badge">{currentUser.display_name || currentUser.email}</span><button className="ghost auth-logout" onClick={logout}>تسجيل الخروج</button></>}</div></header>
    {health?.runtime === 'BLOCKED' && <div className="runtime-warning"><strong>LXC unavailable</strong><span>{health.reason ?? 'هذا المضيف لا يحقق متطلبات Project Computer.'}</span></div>}
    <div id="create-project"><ProjectProvisioningWizard step={wizardStep} prompt={wizardPrompt} platforms={wizardPlatforms} analysis={wizardAnalysis} manifest={wizardManifest} run={wizardRun} busy={wizardBusy} selectedProject={selectedProject} onPromptChange={(event) => setWizardPrompt(event.target.value)} onPlatformsChange={(event) => setWizardPlatforms(event.target.value)} onAnalyze={analyzeWizard} onManifest={createWizardManifest} onProvision={planWizardProvisioning} onReset={() => { setWizardStep(1); setWizardRun(null); setWizardAnalysis(null); setWizardManifest(null) }} /></div>
    <div id="product-intelligence"><ProductExperiencePanel design={designSystem} knowledge={knowledgeGraph} activity={productActivity} computers={projectComputers} impact={impact} impactNode={impactNode} visualQA={visualQA} visualQABusy={visualQABusy} onImpactNodeChange={setImpactNode} onAnalyzeImpact={analyzeImpact} onRunVisualQA={runVisualQA} /></div>
    <section className="hero"><div><span className="eyebrow">LOCAL-FIRST SOFTWARE FACTORY</span><h2>ابنِ داخل كمبيوتر مشروعك.</h2><p>ابدأ من بيئة Linux معزولة، ثم أضف Terminal وFiles وGit وPreview ووكلاء الذكاء الاصطناعي فوق أساس قابل للتحقق.</p></div><div className="formula">PROJECT<br /><b>+</b> RUNTIME<br /><b>+</b> VERIFICATION</div></section>
    <section id="project-computer" className="workspace infrastructure-surface"><div className="section-title"><div><span className="eyebrow">SHARED INFRASTRUCTURE / PROJECT COMPUTERS</span><h3>Project Computer readiness</h3></div><span>{cacheStats ? `${cacheStats.entries ?? 0} cached artifacts` : 'cache status unavailable'}</span></div><div className="grid">{projectComputers.length === 0 && <div className="empty"><strong>No Project Computer record</strong><span>Provisioning remains explicit until a real runtime is available.</span></div>}{projectComputers.map((computer) => <article className="card" key={computer.id}><div className="card-top"><span className={`status status-${computer.status.toLowerCase()}`} />{computer.status}</div><h4>{computer.image}</h4><p className="muted">{computer.runtime_id ?? 'runtime not allocated'}</p><div className="capabilities">{computer.readiness.map((item) => <span key={item}>{item}</span>)}{computer.capabilities.map((item) => <span key={item.capability}>{item.capability}: {item.status}</span>)}</div></article>)}</div>{openComputer && <article className="card open-computer-details"><div className="card-top"><span className={`status status-${openComputer.status.toLowerCase()}`} />{openComputer.status}</div><h4>Project Computer details</h4><p className="muted">{openComputer.image} · {openComputer.runtime_id ?? 'runtime not allocated'}</p><div className="capabilities">{openComputer.readiness.map((item) => <span key={item}>{item}</span>)}{openComputer.capabilities.map((item) => <span key={item.capability}>{item.capability}: {item.status}</span>)}</div><button className="ghost" onClick={() => setOpenComputer(null)}>Close details</button></article>}{environmentResolutions.length > 0 && <div className="resolution-list">{environmentResolutions.map((item) => <div className="event" key={`${item.requirement}-${item.version.version}`}><span>{item.cache_status}</span><p>{item.requirement} {item.version.version} — {item.reason}</p></div>)}</div>}</section>
    <section className="workspace"><div className="section-title"><div><span className="eyebrow">CONTROL PLANE / PROJECTS</span><h3>مشاريعك</h3></div><span>{projects.length} مشروع</span></div>
      <form onSubmit={createProject} className="create"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="اسم المشروع" required /><button disabled={loading}>{loading ? 'جارٍ الإنشاء…' : 'إنشاء Project Computer'}</button></form>
      {error && <div className="error">{error}</div>}
      {health && <div className="health-line"><span>Application: {health.application}</span><span>Runtime host: {health.runtime}</span></div>}
      <div className="grid">{projects.map((project) => <article className="card" key={project.id}><div className="card-top"><span className={`status status-${project.status.toLowerCase()}`} />{project.status}</div><h4>{project.name}</h4><p className="muted">/{project.slug}</p><div className="capabilities"><span>Linux</span><span>Filesystem</span><span>Git</span><span>PTY</span></div><div className="actions">{project.status === 'READY' || project.status === 'STOPPED' ? <button onClick={() => changeStatus(project, 'start')}>Start</button> : null}{project.status === 'RUNNING' ? <button onClick={() => changeStatus(project, 'stop')}>Stop</button> : null}<button className="ghost" onClick={() => openProjectComputer(project)} disabled={openComputerBusy}>{openComputerBusy && selectedProject === project.id ? 'جاري الفتح…' : 'Open Computer'}</button></div></article>)}</div>
      {projects.length === 0 && <div className="empty"><strong>لا توجد مشاريع بعد.</strong><span>أنشئ hello-world لبدء أول vertical slice حقيقي.</span></div>}
    </section>
    <ProjectMembersPanel api={API} projectId={selectedProject} currentUserId={currentUser?.id} globalRole={currentUser?.global_role} />
    <section id="agents" className="workspace agent-surface"><div className="section-title"><div><span className="eyebrow">AGENT FABRIC / NORMALIZED EVENTS</span><h3>Agent Session</h3></div><span>{session?.status ?? 'لا توجد جلسة'}</span></div>
      <div className="worker-grid">{agents.length ? agents.map((agent) => <article className="worker-card" key={agent.id}><div className="card-top"><span className={`status status-${agent.status.toLowerCase()}`} />{agent.display_name}</div><p>{session?.agent_id === agent.id ? session.status : agent.status}</p><span className="muted">{session?.agent_id === agent.id ? `runtime ${session.runtime_id}` : agent.adapter}</span><div className="capabilities"><span>policy guarded</span><span>{session?.agent_id === agent.id ? `${agentEvents.length} events` : 'idle'}</span><span>{verification?.status ?? 'verification pending'}</span></div></article>) : <div className="empty"><strong>No registered agents</strong><span>Agent adapters are loaded from the backend registry.</span></div>}</div>
      <form onSubmit={createAgentSession} className="agent-controls"><select value={selectedProject} onChange={(e) => setSelectedProject(e.target.value)}><option value="">اختر المشروع</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><select value={selectedAgent} onChange={(e) => setSelectedAgent(e.target.value)}>{agents.length ? agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.display_name}</option>) : <option value="codex">Codex</option>}</select><button disabled={!selectedProject}>Create session</button></form>
      {session && <><div className="actions"><button onClick={startAgentSession} disabled={!['CREATED', 'FAILED', 'PAUSED', 'WAITING'].includes(session.status)}>Start / Resume</button><button className="ghost" onClick={cancelAgentSession} disabled={['COMPLETED', 'CANCELLED', 'FAILED'].includes(session.status)}>Cancel</button></div><form onSubmit={sendAgentMessage} className="create"><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Send a provider-neutral agent message" disabled={!['RUNNING', 'WAITING', 'PAUSED'].includes(session.status)} /><button disabled={!message.trim() || !['RUNNING', 'WAITING', 'PAUSED'].includes(session.status)}>Send</button></form></>}
      <div className="governance-panel"><div className="section-title"><div><span className="eyebrow">GOVERNANCE / EXECUTION GUARD</span><h4>Policy preflight</h4></div><span>{governanceDecision?.effect ?? 'NOT_CHECKED'}</span></div><div className="agent-controls"><select value={governancePermission} onChange={(e) => setGovernancePermission(e.target.value)}><option value="terminal.execute">Execute terminal command</option><option value="filesystem.write">Write files</option><option value="git.commit">Create commit</option><option value="git.push">Push Git changes</option><option value="deployment.execute">Deploy</option><option value="database.write">Modify database</option></select><select value={governanceRisk} onChange={(e) => setGovernanceRisk(e.target.value)}><option>READ</option><option>WRITE</option><option>EXECUTE</option><option>DATABASE</option><option>DEPLOY</option><option>PRODUCTION</option></select><input value={governanceResource} onChange={(e) => setGovernanceResource(e.target.value)} placeholder="Resource" /><button onClick={evaluateGovernance} disabled={!selectedProject}>Evaluate policy</button></div>{governanceDecision && <div className={`governance-decision decision-${governanceDecision.effect.toLowerCase()}`}><strong>{governanceDecision.effect}</strong><span>{governanceDecision.reason}</span></div>}</div>
      <div className="event-stream">{agentEvents.length ? agentEvents.map((event, index) => <div className="event" key={`${event.type}-${index}`}><span>{event.type}</span><p>{event.normalized?.text ?? JSON.stringify(event.normalized ?? event.raw ?? {})}</p></div>) : <div className="empty"><strong>لا توجد أحداث بعد.</strong><span>الأحداث المعروضة هنا normalized ولا تقرأ مخرجات CLI مباشرة.</span></div>}</div>
    </section>
    <section id="orchestration" className="workspace workflow-center"><div className="section-title"><div><span className="eyebrow">ORCHESTRATION / TASK GRAPH</span><h3>Workflow</h3></div><span>{workflow?.status ?? 'لا توجد خطة'}</span></div>
      <form onSubmit={createWorkflow} className="create"><input value={workflowGoal} onChange={(e) => setWorkflowGoal(e.target.value)} placeholder="Workflow goal" /><button disabled={!selectedProject}>Create plan</button></form>
      {workflow && <div className="task-graph">{Object.entries(workflow.graph.tasks).map(([id, task]) => <article className="task-node" key={id}><div><strong>{task.title}</strong><span>{task.status}</span></div><p>{task.task_type} · depends on {task.dependencies?.join(', ') || 'none'}</p></article>)}</div>}
    </section>
    <section id="autonomous-loop" className="workspace loop-center"><div className="section-title"><div><span className="eyebrow">PRODUCT LOOP / PERSISTED COORDINATOR</span><h3>Autonomous Loop</h3></div><span>{loop?.status ?? 'NOT_STARTED'}</span></div><div className="create"><input value={loopGoal} onChange={(e) => setLoopGoal(e.target.value)} placeholder="Loop goal" /><button onClick={startAutonomousLoop} disabled={!selectedProject || loopBusy}>{loopBusy ? 'Starting…' : 'Start loop'}</button>{loop && (loop.status === 'BLOCKED' || loop.status === 'FAILED') && <button className="ghost" onClick={resumeAutonomousLoop}>Resume</button>}</div>{loop ? <><div className="loop-progress"><strong>{loop.current_stage || (loop.status === 'COMPLETED' ? 'Completed' : 'Checkpoint persisted')}</strong><span>{loop.error ?? 'Every stage result is persisted by the backend coordinator.'}</span></div><div className="task-graph">{Object.entries(loop.results ?? {}).map(([stage, result]) => <article className="task-node" key={stage}><div><strong>{stage}</strong><span>{result.state}</span></div><p>{result.message}</p></article>)}</div></> : <div className="empty"><strong>No loop execution yet.</strong><span>Start a persisted coordinator; missing runtime capabilities remain BLOCKED_BY_ENVIRONMENT.</span></div>}</section>
    <section id="verification" className="workspace verification-center"><div className="section-title"><div><span className="eyebrow">VERIFICATION / AUTHORITATIVE EVIDENCE</span><h3>Verification Engine</h3></div><span>{verification?.status ?? 'لا توجد نتيجة'}</span></div>
      <div className="create"><button onClick={runVerification} disabled={!selectedProject || verificationBusy}>{verificationBusy ? 'جارٍ التحقق…' : 'Run verification'}</button>{verification && verification.status === 'FAILED' && <button className="ghost" onClick={repairVerification} disabled={verificationBusy}>Analyze and repair</button>}</div>
      {verification ? <><div className="verification-grid">{verification.results.map((result) => <article className="verification-check" key={result.check_id}><div><strong>{result.check_id}</strong><span className={`status-text status-${result.status.toLowerCase()}`}>{result.status}</span></div><small>{result.failure?.failure_type ?? `exit ${result.evidence?.exit_code ?? 0}`}</small><p>{result.failure?.suspected_cause ?? result.evidence?.stdout ?? 'Evidence recorded'}</p></article>)}</div><div className="health-line"><span>Required: {verification.summary.required_passed} passed / {verification.summary.required_failed} failed</span><span>State: {verification.state?.commit_sha ?? 'unknown commit'} · {verification.state?.worktree ?? 'unknown worktree'}</span></div>{verification.repairs.length > 0 && <div className="event-stream">{verification.repairs.map((repair) => <div className="event" key={repair.attempt}><span>repair attempt {repair.attempt}</span><p>{repair.status} {repair.error ?? ''}</p></div>)}</div>}</> : <div className="empty"><strong>No verification run yet.</strong><span>Agent completion is not proof; this panel displays runtime-scoped evidence and the authoritative decision.</span></div>}
    </section>
    <section id="ai-control" className="workspace ai-center"><div className="section-title"><div><span className="eyebrow">SUDA AI FABRIC / RUNTIMES + HARDWARE</span><h3>AI Control Center</h3></div><span>{aiModels.length} discovered models</span></div>
      <div className="ai-overview"><div><strong>Runtimes</strong><span>{aiRuntimes.length ? aiRuntimes.map((item) => `${item.spec.kind}: ${item.health.status}`).join(' · ') : 'No configured local runtimes'}</span></div><div><strong>Hardware</strong><span>{hardware ? `${hardware.cpu_cores} CPU · ${Math.round(hardware.memory_available / 1024 / 1024 / 1024)} GB available RAM · ${hardware.gpu_count} GPU` : 'Unavailable'}</span></div><div><strong>Project policy</strong><select value={aiPolicy} onChange={(e) => setAiPolicy(e.target.value)}><option>BALANCED</option><option>LOCAL_FIRST</option><option>CLOUD_FIRST</option><option>CHEAPEST</option><option>PRIVACY_FIRST</option></select><label><input type="checkbox" checked={aiLocalOnly} onChange={(e) => setAiLocalOnly(e.target.checked)} /> local only</label><button onClick={saveAISettings}>Save policy</button></div></div>
      <div className="model-grid">{aiModels.map((model) => <article className="model-card" key={`${model.runtime_id}-${model.id}`}><div><strong>{model.display_name}</strong><span>{model.runtime_id} · {model.status}</span></div><p>{model.context_window ? `${(model.context_window / 1000).toFixed(0)}K context` : 'context unknown'} · {model.local ? 'LOCAL' : 'REMOTE'} · {model.capabilities?.CODING ? 'coding' : 'general'}</p></article>)}</div>
    </section>
    <section id="deployment" className="workspace deployment-center"><div className="section-title"><div><span className="eyebrow">HOSTING / RELEASE → DEPLOY → HEALTH → ROLLBACK</span><h3>Deployment Workspace</h3></div><span>{deployments.length} deployments</span></div>
      <form onSubmit={createDeployment} className="agent-controls"><select value={deployEnvironment} onChange={(e) => setDeployEnvironment(e.target.value)}><option value="development">Development</option><option value="preview">Preview</option><option value="production">Production</option></select><input value={deployVersion} onChange={(e) => setDeployVersion(e.target.value)} placeholder="Version" /><input value={deployRevision} onChange={(e) => setDeployRevision(e.target.value)} placeholder="Git revision" /><input value={deployRuntime} onChange={(e) => setDeployRuntime(e.target.value)} placeholder="Project runtime ID" /><input value={deployHealthTarget} onChange={(e) => setDeployHealthTarget(e.target.value)} placeholder="Runtime health command" /><button disabled={!selectedProject || !verification}>Deploy verified release</button></form>
      <div className="deployment-list">{deployments.length ? deployments.map((item) => <article className="deployment-card" key={item.id}><div><strong>{item.version || item.id}</strong><span className={`status-text status-${item.status.toLowerCase()}`}>{item.status}</span></div><p>{item.environment} · {item.source_revision} · health {item.health_status ?? 'pending'}</p>{item.failure_reason && <small>{item.failure_reason}</small>}{item.status === 'ACTIVE' && <button className="ghost" onClick={() => rollbackDeployment(item.id)}>Rollback</button>}</article>) : <div className="empty"><strong>No deployments yet.</strong><span>Deployment is blocked until a persisted authoritative verification run is selected.</span></div>}</div>
    </section>
    <section id="models" className="workspace model-center"><div className="section-title"><div><span className="eyebrow">MODEL FABRIC / DETERMINISTIC ROUTING</span><h3>Model Center</h3></div><span>{models.length} models</span></div>
      <div className="model-grid">{models.map((model) => <article className="model-card" key={model.id}><div><strong>{model.display_name}</strong><span>{model.provider_id} · {model.local ? 'LOCAL' : 'REMOTE'}</span></div><p>{model.context_window.toLocaleString()} context · {model.coding ? 'coding' : 'general'} · {model.tool_use ? 'tools' : 'no tools'}</p></article>)}</div>
      <form onSubmit={previewRouting} className="agent-controls"><select value={routingPolicy} onChange={(e) => setRoutingPolicy(e.target.value)}><option>BALANCED</option><option>BEST</option><option>CHEAPEST</option><option>FASTEST</option><option>LOCAL_FIRST</option></select><button disabled={!models.length}>Preview routing</button></form>
      {routingDecision && <div className="routing-result"><strong>Selected: {routingDecision.selected_model?.model_id ?? 'BLOCKED'}</strong><span>{routingDecision.reason}</span><small>Alternatives: {routingDecision.alternatives?.map((item) => item.model.model_id).join(', ') || 'none'} · estimated cost: {routingDecision.estimated_cost ?? 0}</small></div>}
    </section>
  </main>
}
