import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Project = { id: string; name: string; slug: string; status: string; runtime_id?: string }
type Health = { application: string; runtime: string; reason?: string }
type Agent = { id: string; display_name: string; adapter: string; status: string }
type AgentSession = { id: string; project_id: string; agent_id: string; status: string; runtime_id: string; working_directory: string }
type AgentEvent = { type: string; normalized?: { text?: string }; raw?: Record<string, unknown> }
type Model = { id: string; provider_id: string; display_name: string; context_window: number; local: boolean; remote: boolean; coding: boolean; reasoning: boolean; tool_use: boolean }
type RoutingDecision = { selected_model?: { provider_id: string; model_id: string }; reason?: string; alternatives?: { model: { provider_id: string; model_id: string }; score: number }[]; estimated_cost?: number; confidence?: number }
type Workflow = { id: string; goal: string; status: string; strategy: string; graph: { tasks: Record<string, { title: string; status: string; dependencies: string[]; task_type: string }> } }
type Verification = { id: string; status: string; project_id: string; summary: { required_passed: number; required_failed: number; optional_passed: number; optional_failed: number; blocked: number }; results: { check_id: string; status: string; evidence?: { exit_code?: number; stdout?: string; stderr?: string; commit_sha?: string }; failure?: { failure_type: string; suspected_cause: string } }[]; failures: { failure_type: string; check_id: string; suspected_cause: string }[]; repairs: { attempt: number; status: string; error?: string }[]; state?: { commit_sha?: string; worktree?: string } }
type AIRuntime = { spec: { id: string; kind: string; endpoint: string; local: boolean }; capabilities: Record<string, boolean>; health: { status: string; latency?: number; available_models?: string[]; error?: string } }
type AIModel = { id: string; runtime_id: string; display_name: string; status: string; context_window: number; local: boolean; capabilities: Record<string, boolean>; latency?: number }
type Hardware = { cpu_cores: number; memory_total: number; memory_available: number; gpu_count: number; gpu_memory_total: number; gpus?: { id: string; model: string; memory_total: number; memory_available: number }[] }
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:8080'

export default function App() {
  const [projects, setProjects] = useState<Project[]>([])
  const [name, setName] = useState('hello-world')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [health, setHealth] = useState<Health | null>(null)
  const [agents, setAgents] = useState<Agent[]>([])
  const [selectedProject, setSelectedProject] = useState('')
  const [selectedAgent, setSelectedAgent] = useState('codex')
  const [session, setSession] = useState<AgentSession | null>(null)
  const [agentEvents, setAgentEvents] = useState<AgentEvent[]>([])
  const [message, setMessage] = useState('')
  const [models, setModels] = useState<Model[]>([])
  const [routingPolicy, setRoutingPolicy] = useState('BALANCED')
  const [routingDecision, setRoutingDecision] = useState<RoutingDecision | null>(null)
  const [workflowGoal, setWorkflowGoal] = useState('Build and verify a small feature')
  const [workflow, setWorkflow] = useState<Workflow | null>(null)
  const [verification, setVerification] = useState<Verification | null>(null)
  const [verificationBusy, setVerificationBusy] = useState(false)
  const [aiRuntimes, setAiRuntimes] = useState<AIRuntime[]>([])
  const [aiModels, setAiModels] = useState<AIModel[]>([])
  const [hardware, setHardware] = useState<Hardware | null>(null)
  const [aiPolicy, setAiPolicy] = useState('BALANCED')
  const [aiLocalOnly, setAiLocalOnly] = useState(false)
  async function loadProjects(): Promise<Project[]> { const response = await fetch(`${API}/api/v1/projects`); if (!response.ok) throw new Error('تعذر تحميل المشاريع'); const items: Project[] = await response.json(); setProjects(items); return items }
  useEffect(() => { loadProjects().then((items) => { if (items[0]) setSelectedProject(items[0].id) }).catch((err) => setError(err.message)); fetch(`${API}/health`).then((response) => response.json()).then(setHealth).catch(() => setHealth({ application: 'UNKNOWN', runtime: 'UNKNOWN' })); fetch(`${API}/api/agents`).then((response) => response.ok ? response.json() : []).then(setAgents).catch(() => setAgents([])); fetch(`${API}/api/models`).then((response) => response.ok ? response.json() : []).then(setModels).catch(() => setModels([])); fetch(`${API}/api/ai/runtimes`).then((response) => response.ok ? response.json() : []).then(setAiRuntimes).catch(() => setAiRuntimes([])); fetch(`${API}/api/ai/models`).then((response) => response.ok ? response.json() : []).then(setAiModels).catch(() => setAiModels([])); fetch(`${API}/api/ai/hardware`).then((response) => response.ok ? response.json() : null).then(setHardware).catch(() => setHardware(null)) }, [])
  async function saveAISettings() { if (!selectedProject) return; const response = await fetch(`${API}/api/projects/${selectedProject}/ai-settings`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ routing_policy: aiPolicy, privacy_policy: aiLocalOnly ? 'PRIVATE' : 'PUBLIC', local_only: aiLocalOnly }) }); if (!response.ok) setError('تعذر حفظ إعدادات AI للمشروع') }
  async function createProject(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch(`${API}/api/v1/projects`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); if (!response.ok) throw new Error((await response.json()).error?.message ?? 'فشل إنشاء المشروع'); setName(''); await loadProjects() } catch (err) { setError(err instanceof Error ? err.message : 'حدث خطأ غير معروف') } finally { setLoading(false) } }
  async function changeStatus(project: Project, action: 'start' | 'stop') { setError(''); try { const response = await fetch(`${API}/api/v1/projects/${project.id}/${action}`, { method: 'POST' }); if (!response.ok) throw new Error((await response.json()).error?.message ?? 'فشل تغيير الحالة'); await loadProjects() } catch (err) { setError(err instanceof Error ? err.message : 'حدث خطأ غير معروف') } }
  async function createAgentSession(event: FormEvent) { event.preventDefault(); if (!selectedProject) { setError('اختر مشروعًا أولًا'); return }; setError(''); try { const response = await fetch(`${API}/api/projects/${selectedProject}/agent-sessions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agent_id: selectedAgent, runtime_id: `${selectedProject}_runtime`, working_directory: '/workspace' }) }); if (!response.ok) throw new Error((await response.json()).error?.message ?? 'تعذر إنشاء الجلسة'); setSession(await response.json()); setAgentEvents([]) } catch (err) { setError(err instanceof Error ? err.message : 'حدث خطأ غير معروف') } }
  async function sendAgentMessage(event: FormEvent) { event.preventDefault(); if (!session || !message.trim()) return; const response = await fetch(`${API}/api/projects/${session.project_id}/agent-sessions/${session.id}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message }) }); if (!response.ok) setError((await response.json()).error?.message ?? 'تعذر إرسال الرسالة'); setMessage(''); const events = await fetch(`${API}/api/projects/${session.project_id}/agent-sessions/${session.id}/events`).then((r) => r.ok ? r.json() : []); setAgentEvents(events) }
  async function previewRouting(event: FormEvent) { event.preventDefault(); const response = await fetch(`${API}/api/model-routing/decide`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project_id: selectedProject, agent_id: selectedAgent, policy: routingPolicy, privacy_policy: 'PUBLIC', local_policy: 'REMOTE_ALLOWED', available_runtime: true, task_profile: { task_type: 'REFACTOR', context_required: 1000, reasoning_required: true, privacy_classification: 'PUBLIC' } }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error ?? 'لا يوجد نموذج متوافق'); setRoutingDecision(payload.decision ?? null); return }; setRoutingDecision(payload) }
  async function createWorkflow(event: FormEvent) { event.preventDefault(); if (!selectedProject) { setError('اختر مشروعًا أولًا'); return }; const response = await fetch(`${API}/api/projects/${selectedProject}/workflows`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ intent: { goal: workflowGoal } }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error?.message ?? 'تعذر إنشاء workflow'); return }; setWorkflow(payload) }
  async function runVerification() { if (!selectedProject) { setError('اختر مشروعًا أولًا'); return }; setVerificationBusy(true); setError(''); try { const response = await fetch(`${API}/api/verifications`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project_id: selectedProject, workflow_id: workflow?.id, profile: 'standard', policy: 'STANDARD', runtime_id: `${selectedProject}_runtime`, workspace: '/workspace', checks: [{ id: 'build', type: 'BUILD', name: 'Build', required: true, timeout: 600000000000, retry_policy: { max_attempts: 1 }, configuration: { argv: ['go', 'build', './...'] } }, { id: 'tests', type: 'UNIT_TEST', name: 'Tests', required: true, timeout: 600000000000, retry_policy: { max_attempts: 1 }, configuration: { argv: ['go', 'test', './...'] }, dependencies: ['build'] }] }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? 'تعذر تشغيل verification'); setVerification(payload) } catch (err) { setError(err instanceof Error ? err.message : 'تعذر تشغيل verification') } finally { setVerificationBusy(false) } }
  async function repairVerification() { if (!verification) return; setVerificationBusy(true); try { const response = await fetch(`${API}/api/verifications/${verification.id}/repair`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ runtime_id: `${selectedProject}_runtime`, workspace: '/workspace', max_attempts: 3 }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? 'تعذر بدء repair'); setVerification(payload) } catch (err) { setError(err instanceof Error ? err.message : 'تعذر بدء repair') } finally { setVerificationBusy(false) } }
  return <main dir="rtl">
    <header><div><span className="eyebrow">SUDA TECHNOLOGIES</span><h1>SUDA FORGE</h1><p>كل مشروع هو Project Computer حقيقي، وليس مجرد مجلد أو نافذة محادثة.</p></div><div className="system"><span className="dot" /> Control Plane online</div></header>
    {health?.runtime === 'BLOCKED' && <div className="runtime-warning"><strong>LXC unavailable</strong><span>{health.reason ?? 'هذا المضيف لا يحقق متطلبات Project Computer.'}</span></div>}
    <section className="hero"><div><span className="eyebrow">LOCAL-FIRST SOFTWARE FACTORY</span><h2>ابنِ داخل كمبيوتر مشروعك.</h2><p>ابدأ من بيئة Linux معزولة، ثم أضف Terminal وFiles وGit وPreview ووكلاء الذكاء الاصطناعي فوق أساس قابل للتحقق.</p></div><div className="formula">PROJECT<br /><b>+</b> RUNTIME<br /><b>+</b> VERIFICATION</div></section>
    <section className="workspace"><div className="section-title"><div><span className="eyebrow">CONTROL PLANE / PROJECTS</span><h3>مشاريعك</h3></div><span>{projects.length} مشروع</span></div>
      <form onSubmit={createProject} className="create"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="اسم المشروع" required /><button disabled={loading}>{loading ? 'جارٍ الإنشاء…' : 'إنشاء Project Computer'}</button></form>
      {error && <div className="error">{error}</div>}
      {health && <div className="health-line"><span>Application: {health.application}</span><span>Runtime host: {health.runtime}</span></div>}
      <div className="grid">{projects.map((project) => <article className="card" key={project.id}><div className="card-top"><span className={`status status-${project.status.toLowerCase()}`} />{project.status}</div><h4>{project.name}</h4><p className="muted">/{project.slug}</p><div className="capabilities"><span>Linux</span><span>Filesystem</span><span>Git</span><span>PTY</span></div><div className="actions">{project.status === 'READY' || project.status === 'STOPPED' ? <button onClick={() => changeStatus(project, 'start')}>Start</button> : null}{project.status === 'RUNNING' ? <button onClick={() => changeStatus(project, 'stop')}>Stop</button> : null}<button className="ghost">Open Computer</button></div></article>)}</div>
      {projects.length === 0 && <div className="empty"><strong>لا توجد مشاريع بعد.</strong><span>أنشئ hello-world لبدء أول vertical slice حقيقي.</span></div>}
    </section>
    <section className="workspace agent-surface"><div className="section-title"><div><span className="eyebrow">AGENT FABRIC / NORMALIZED EVENTS</span><h3>Agent Session</h3></div><span>{session?.status ?? 'لا توجد جلسة'}</span></div>
      <form onSubmit={createAgentSession} className="agent-controls"><select value={selectedProject} onChange={(e) => setSelectedProject(e.target.value)}><option value="">اختر المشروع</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><select value={selectedAgent} onChange={(e) => setSelectedAgent(e.target.value)}>{agents.length ? agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.display_name}</option>) : <option value="codex">Codex</option>}</select><button disabled={!selectedProject}>Create session</button></form>
      {session && <form onSubmit={sendAgentMessage} className="create"><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Send a provider-neutral agent message" /><button disabled={!message.trim()}>Send</button></form>}
      <div className="event-stream">{agentEvents.length ? agentEvents.map((event, index) => <div className="event" key={`${event.type}-${index}`}><span>{event.type}</span><p>{event.normalized?.text ?? JSON.stringify(event.normalized ?? event.raw ?? {})}</p></div>) : <div className="empty"><strong>لا توجد أحداث بعد.</strong><span>الأحداث المعروضة هنا normalized ولا تقرأ مخرجات CLI مباشرة.</span></div>}</div>
    </section>
    <section className="workspace workflow-center"><div className="section-title"><div><span className="eyebrow">ORCHESTRATION / TASK GRAPH</span><h3>Workflow</h3></div><span>{workflow?.status ?? 'لا توجد خطة'}</span></div>
      <form onSubmit={createWorkflow} className="create"><input value={workflowGoal} onChange={(e) => setWorkflowGoal(e.target.value)} placeholder="Workflow goal" /><button disabled={!selectedProject}>Create plan</button></form>
      {workflow && <div className="task-graph">{Object.entries(workflow.graph.tasks).map(([id, task]) => <article className="task-node" key={id}><div><strong>{task.title}</strong><span>{task.status}</span></div><p>{task.task_type} · depends on {task.dependencies?.join(', ') || 'none'}</p></article>)}</div>}
    </section>
    <section className="workspace verification-center"><div className="section-title"><div><span className="eyebrow">VERIFICATION / AUTHORITATIVE EVIDENCE</span><h3>Verification Engine</h3></div><span>{verification?.status ?? 'لا توجد نتيجة'}</span></div>
      <div className="create"><button onClick={runVerification} disabled={!selectedProject || verificationBusy}>{verificationBusy ? 'جارٍ التحقق…' : 'Run verification'}</button>{verification && verification.status === 'FAILED' && <button className="ghost" onClick={repairVerification} disabled={verificationBusy}>Analyze and repair</button>}</div>
      {verification ? <><div className="verification-grid">{verification.results.map((result) => <article className="verification-check" key={result.check_id}><div><strong>{result.check_id}</strong><span className={`status-text status-${result.status.toLowerCase()}`}>{result.status}</span></div><small>{result.failure?.failure_type ?? `exit ${result.evidence?.exit_code ?? 0}`}</small><p>{result.failure?.suspected_cause ?? result.evidence?.stdout ?? 'Evidence recorded'}</p></article>)}</div><div className="health-line"><span>Required: {verification.summary.required_passed} passed / {verification.summary.required_failed} failed</span><span>State: {verification.state?.commit_sha ?? 'unknown commit'} · {verification.state?.worktree ?? 'unknown worktree'}</span></div>{verification.repairs.length > 0 && <div className="event-stream">{verification.repairs.map((repair) => <div className="event" key={repair.attempt}><span>repair attempt {repair.attempt}</span><p>{repair.status} {repair.error ?? ''}</p></div>)}</div>}</> : <div className="empty"><strong>No verification run yet.</strong><span>Agent completion is not proof; this panel displays runtime-scoped evidence and the authoritative decision.</span></div>}
    </section>
    <section className="workspace ai-center"><div className="section-title"><div><span className="eyebrow">SUDA AI FABRIC / RUNTIMES + HARDWARE</span><h3>AI Control Center</h3></div><span>{aiModels.length} discovered models</span></div>
      <div className="ai-overview"><div><strong>Runtimes</strong><span>{aiRuntimes.length ? aiRuntimes.map((item) => `${item.spec.kind}: ${item.health.status}`).join(' · ') : 'No configured local runtimes'}</span></div><div><strong>Hardware</strong><span>{hardware ? `${hardware.cpu_cores} CPU · ${Math.round(hardware.memory_available / 1024 / 1024 / 1024)} GB available RAM · ${hardware.gpu_count} GPU` : 'Unavailable'}</span></div><div><strong>Project policy</strong><select value={aiPolicy} onChange={(e) => setAiPolicy(e.target.value)}><option>BALANCED</option><option>LOCAL_FIRST</option><option>CLOUD_FIRST</option><option>CHEAPEST</option><option>PRIVACY_FIRST</option></select><label><input type="checkbox" checked={aiLocalOnly} onChange={(e) => setAiLocalOnly(e.target.checked)} /> local only</label><button onClick={saveAISettings}>Save policy</button></div></div>
      <div className="model-grid">{aiModels.map((model) => <article className="model-card" key={`${model.runtime_id}-${model.id}`}><div><strong>{model.display_name}</strong><span>{model.runtime_id} · {model.status}</span></div><p>{model.context_window ? `${(model.context_window / 1000).toFixed(0)}K context` : 'context unknown'} · {model.local ? 'LOCAL' : 'REMOTE'} · {model.capabilities?.CODING ? 'coding' : 'general'}</p></article>)}</div>
    </section>
    <section className="workspace model-center"><div className="section-title"><div><span className="eyebrow">MODEL FABRIC / DETERMINISTIC ROUTING</span><h3>Model Center</h3></div><span>{models.length} models</span></div>
      <div className="model-grid">{models.map((model) => <article className="model-card" key={model.id}><div><strong>{model.display_name}</strong><span>{model.provider_id} · {model.local ? 'LOCAL' : 'REMOTE'}</span></div><p>{model.context_window.toLocaleString()} context · {model.coding ? 'coding' : 'general'} · {model.tool_use ? 'tools' : 'no tools'}</p></article>)}</div>
      <form onSubmit={previewRouting} className="agent-controls"><select value={routingPolicy} onChange={(e) => setRoutingPolicy(e.target.value)}><option>BALANCED</option><option>BEST</option><option>CHEAPEST</option><option>FASTEST</option><option>LOCAL_FIRST</option></select><button disabled={!models.length}>Preview routing</button></form>
      {routingDecision && <div className="routing-result"><strong>Selected: {routingDecision.selected_model?.model_id ?? 'BLOCKED'}</strong><span>{routingDecision.reason}</span><small>Alternatives: {routingDecision.alternatives?.map((item) => item.model.model_id).join(', ') || 'none'} · estimated cost: {routingDecision.estimated_cost ?? 0}</small></div>}
    </section>
  </main>
}
